name: Docs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup DocFX
      run: dotnet tool install docfx
      continue-on-error: false

    - name: Restore .NET projects
      run: dotnet restore
      continue-on-error: false
      
    - name: DocFX Build
      run: docfx .\docfx_project\docfx.json
      continue-on-error: false

    - name: List files (Debug)
      working-directory: docfx_project
      run: dir
      
    - name: Publish
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/_site
        force_orphan: true
